---
title: "Agenda"
output:
  html_document:
    includes:
      in_header: agenda-cover.html
---

<center>

## A tentative schedule for the day of the wedding is as follows:

### **1:00 - 1:30 PM**

### Recommended travel time to get to property in Queen's Bay, BC from your accommodation. We will provide all confirmed attendees with address well in advanced of the day. We will also be setting up a carpooling sheet well in advanced to reduce the number of cars on the road.

### **2:00 - 2:30 PM**

### Wedding ceremony at family property in Queen's Bay, BC

### **2:30 - 4:30 PM **

### Cocktails, light snacks, mingling, and photos on the property

### **4:30 - 5:00 PM**

### Recommended travel time to return to Nelson, BC (you are of course welcome to leave earlier)

### **5:30 PM - late**

### Reception at The Spirit Bar at the Hume Hotel in Nelson, BC

#### Note that this schedule may change slightly closer to the day, but we will send information to all attendees well in advanced of the day.
