---
title: "Q&A"
output:
  html_document:
    includes:
      in_header: qa-cover.html
---

<center>

### **Are there any pre- or post-wedding events?**

### There are no official pre-wedding events planned yet! However, we may go for a hike in the area a day or two before the wedding. We will make sure to figure out who is already in the area and get in contact with you!

### We ARE planning to be in the Rockies from 10 - 16 September. Note that this is NOT our honeymoon, and we would be more than happy for people to join us if you were also hoping to hit up the Rockies while you are in the area!! Feel free to contact us for more information. Note that we recommend that you look into this soon if you are thinking of going, as the Rockies book up fast this time of year.

### **Will there be a Stag & Doe?**

### Yes! We will be having a Stag & Doe in Point Edward, Ontario (near Brandon's hometown) on Saturday, 1 June 2024. Tickets are NOW ON SALE! If you would like tickets to the Stag & Doe, or raffle tickets for the grand prize, please contact Allison or Brandon. Even if you are not attending, please feel free to buy a ticket for your chance to win some great prizes! For those of you outside Ontario, [see this Wikipedia article](https://en.wikipedia.org/wiki/Stag_and_doe) about what a Stag & Doe is!

### **Are children welcome?**

### Yes! Children may come to the ceremony, and may join us at the reception until 9:30 PM when the bar becomes strictly 19+.



### **Is this wedding indoor or outdoors?**

### We are hoping for outdoor ceremony with an indoor reception, but will have weather plans in place!

### **What about transportation between the ceremony and reception?**

### The wedding ceremony is about a 30 minute drive from Nelson, BC where we will be having the reception. There is ample parking available at the ceremony site, but we will also set up a carpooling list for those who would like to carpool to and from the ceremony.


### **What should I wear?**

### Dressy casual or cocktail. The ceremony location may have some uneven ground, so make sure you wear shoes that you are comfortable wearing on grass!

### **Will you be feeding us?**

### Yes, more details about the menu to follow.

### **What about a gift registry?**

### Your presence is a good enough present! We realize the costs associated with getting and staying here to celebrate with us, and so we are not asking for gifts. If you would like to contribute to our honeymoon, we of course would be incredibly grateful. Details coming soon...

</center>