---
title: "Travel"
output:
  html_document:
    includes:
      in_header: travel-cover.html
---

<center>

### We are so excited to have so many of you coming from out of town. We have tried to make things as easy as possible for you to figure out travel plans, what to do when you are here, etc.

### Due to the remote and rural location of our wedding, you will most likely need to fly into an airport, rent a car, and drive the rest of the way to your accomodations in Nelson (or nearby). We will be creating a carpool list after invites are sent out to help facilitate splitting rental cars, for folks arriving and leaving at similar times. Stay tuned for that.

### 1. [Airports](#airports-1)
### 2. [Attractions](#attractions-1)
### 3. [Accomodations](#accomodations-1)

# **Airports**
### You have a few nearby airport options to choose from. [West Kootenay Regional Airport (YCG)](https://maps.app.goo.gl/cMAuDgwjrMHQdRKj6) in Castlegar, BC will be the closest airport to Nelson, BC. You can rent a car from [PractiCar](https://www.practicar.ca/), located right at the airport, and drive the remaining 30-40 minutes to arrive at Nelson, BC. Alternatively, you may choose to fly into [Kelowna International Airport (YLW)](https://maps.app.goo.gl/zhhtMhs2sVcFuS6T9) in Kelowna, BC. Located approximately 4 hours from Nelson, YLW has Enterprise Rent-a-Car options for you to pick up a rental car.

### If you fancy a longer road trip, you may consider flying into [Calgary International Airport (YYC)](https://maps.app.goo.gl/mhp787QxGToc64De6), located in the next province over in Calgary, Alberta. From here, you may rent a car from one of the [many car rental companies](https://www.yyc.com/en-us/navigatingyyc/groundtransportation/carrentals.aspx), explore the exciting city of Calgary, AB, and then take a road trip through Canada's famed Rocky Mountains. This road trip can include stops to Banff National Park, Jasper National Park (via the amazing Icefields Parkway), Kootenay National Park, Fairmont Hot Springs, among several other beautiful stops. We recommend taking a few days to do this if you want to experience the magic of the Rocky Mountains.

### Finally, for a British Columbia roadtrip that is sure to impress, you may consider flying into [Vancouver International Airport (YVR)](https://maps.app.goo.gl/X8tgssS7PckyiMYw8), located in Vancouver, BC. YVR has several options to rent a car directly from the airport, or you may choose to stay in Vancouver for a day or two to explore the sights of this beautiful coastal city. From here, you may then begin your road trip across British Columbia, which includes driving along the Fraser Valley, the Okanagan Valley (if you are a fan of wine, you'll love this area), and the (almost) desert region of Osoyoos. This is the road trip Allie and her family have done every year since she was a child, and it still has not gotten old!

# **Attractions**

### There are endless things to do and see in this region of the world. The region is known for its lovely hikes ranging from easy to strenuous (bring bear spray if you do go on hikes!), and the lake is still nice to swim in in early September. We have listed some of these below, both in the Nelson/Kootenay region, and further afield for those interested in a road trip. We will add more items as we remember things, but definitely know that this is not an exhaustive list.


## Nelson and Kootenay Region:

 <h4> Kokanee Creek PP
  
  Kokanee Glacier
  
  Road Kings classic car show
  
  Nelson BC Baker street
  
  Town of Kaslo
  
  Fleming College Arboretum
  
  Ainsworth Hot Springs</h4>
  
## Interior British Columbia

<h4>
Okanagan Valley Wineries
</h4>

## Further Afield

<h4>
Jasper National Park

Banff National Park

Glacier National Park</h4>


# **Accomodations**

### There are several options in town and out for accomodations. We would suggest at the very least staying in town the night of the wedding (i.e., the night of September 7th), but there are several other lovely accomodations nearby if you choose to stay a while. **You should consider booking sooner rather than later if you know you are going to be able to make it.**

### Here are some options for you to take a look at to start, but it is certainly not an exhaustive list:

 <h4> [The Hume Hotel & Spa](https://www.humehotel.com/)
  
  [The Adventure Hotel](https://adventurehotel.ca/)
  
  [Best Western Plus Baker Street Inn](https://www.bestwestern.com/en_US/book/hotels-in-nelson/best-western-plus-baker-street-inn/propertyCode.62096.html)
  
  [Dancing Bear Inn](https://dancingbearinn.com/)
  
  [Cloudside Hotel](https://cloudside.ca/)
  
  [Prestige Lakeside Resort](https://www.prestigehotelsandresorts.com/locations/nelson-lakeside-resort/overview/)
  
  [Prestige Inn](https://www.prestigehotelsandresorts.com/locations/nelson-prestige-inn/overview/)</h4>
  
### We also highly recommend checking out [booking.com](https://www.booking.com/) or [Airbnb](https://www.airbnb.com/) (or any of the other 3rd party sites) for the Nelson area as well. There are a tonne of lovely options for both Nelson townsite and further out. We recommend booking earlier as this is a popular place this time of year, and we recommend staying in Nelson the night of the wedding as remote travel to return to accomodations can sometimes be difficult.

</center>